### ISSUE TITLE
Calculated output metrics

### ISSUE THREAD

**Issue by hoelzer** [hoelzer-lab/president#2]
The script should provide __three different output metrics__ to assess the quality of the query sequence in comparison to the reference sequence. The rationale behind this is, that ambiguous bases (Ns) can be counted differently when it comes to the calculation of sequence identity. 

We basically aim to answer three questions: 
a) Is the input query sequence the same species as the reference sequence (high ANI)? --> percent sequence identity
b) How is the quality in regard to ambiguous Ns?
c) Coverage?

### a)
* count positions in query that match the reference (ACGT)
* `matches / query_length` 
* ... or in other words: `(query_length - hamming_distance_ignoring_Ns) / query_length)`

### b)
* count number of Ns in query sequence
* `(query_number_Ns + query_gaps_in_aln) / query_length` 

### c) 
* count number of matches and mismatches in aln (ACGT), gaps and Ns do not count!
* `(matches + mismatches) / reference_length` 
* ... or in other words: `(length_query - query_number_Ns_and_gaps) / reference_length`

**Comment by phiweger** [comment]
done

**Comment by hoelzer** [comment]
Great! I tested:

```
python pairwise_nucleotide_identity.py -r NC_045512.2.fasta -q NC_045512.2.20mis.fasta
```

### output:
```
Running Mafft ...
0.9987 nucleotide identity
0.9994 nucleotide identity (excluding non-ACTG)
20 non-ACTG symbols out of 29903
```

Looks good!
